name: '2.bonus::test_ban'

on:
  pull_request:
    types: [ opened, edited, synchronize ]
    paths:
      - 'tasks/main.py'
      - 'tasks/driver/files/commands.py'
      - 'tasks/driver/network/commands.py'
      - 'resources/scripts/'
      - 'test/main/s2/test_bonus.py'
      - '.github/workflows/bonus$ban.yaml'
  workflow_dispatch:

jobs:
  test-ban:
    timeout-minutes: 1
    name: 'test-ban'
    runs-on: [ self-hosted, ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: dev
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest decorator requests
      - run: |
          pytest test/main/s2/test_bonus.py::TestBonus.py::test_ban