name: '2.bonus::test_process'

on:
  push:
    paths:
      - './tests/main/s2/test_bonus.py'
      - '.github/workflows/bonus$process.yaml'
  workflow_dispatch:

jobs:
  test-process:
    timeout-minutes: 1
    name: 'test-process'
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: dev
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest decorator requests
      - run: |
          pytest ./tests/main/s2/test_bonus.py::TestBonus.py::test_process