name: '1.config::test_no_display'

on:
  pull_request:
    types: [ opened, edited, synchronize ]
    paths:
      - 'tasks/main.py'
      - 'tasks/driver/files/commands.py'
      - 'tasks/driver/network/commands.py'
      - 'resources/scripts/'
      - 'test/main/s1/test_config.py'
      - '.github/workflows/config$no_display.yaml'
  workflow_dispatch:

jobs:
  test-no_display:
    timeout-minutes: 1
    name: 'test-no_display'
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: dev
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest decorator requests
      - run: |
          pytest test/main/s1/test_config.py::TestConfig.py::test_no_display