name: '1.config::test_no_display'

on:
  pull-request:
    types: [ opened, edited, synchronize ]
    paths:
      - './tests/main/s1/test_config.py'
      - '.github/workflows/config$no_display.yaml'
  workflow_dispatch:

jobs:
  test-no_display:
    timeout-minutes: 1
    name: 'test-no_display'
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: dev
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest decorator requests
      - run: |
          pytest ./tests/main/s1/test_config.py::TestConfig.py::test_no_display