name: '2.edit::test_type'

on:
  pull-request:
    types: [ opened, edited, synchronize ]
    paths:
      - './tests/main/s2/test_edit.py'
      - '.github/workflows/edit$type.yaml'
  workflow_dispatch:

jobs:
  test-type:
    timeout-minutes: 1
    name: 'test-type'
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: dev
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest decorator requests
      - run: |
          pytest ./tests/main/s2/test_edit.py::TestEdit.py::test_type