name: '2.example::test_example_square'

on:
  pull-request:
    types: [ opened, edited, synchronize ]
    paths:
      - './tests/main/s2/test_example.py'
      - '.github/workflows/example$example_square.yaml'
  workflow_dispatch:

jobs:
  test-example_square:
    timeout-minutes: 1
    name: 'test-example_square'
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: dev
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest decorator requests
      - run: |
          pytest ./tests/main/s2/test_example.py::TestExample.py::test_example_square