name: '2.find::test_find_many'

on:
  pull_request:
    types: [ opened, edited, synchronize ]
    paths:
      - 'tasks/main.py'
      - 'tasks/driver/files/commands.py'
      - 'tasks/driver/network/commands.py'
      - 'resources/scripts/'
      - 'test/main/s2/test_find.py'
      - '.github/workflows/find$find_many.yaml'
  workflow_dispatch:

jobs:
  test-find_many:
    timeout-minutes: 1
    name: 'test-find_many'
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: dev
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest decorator requests
      - run: |
          pytest test/main/s2/test_find.py::TestFind.py::test_find_many