name: '2.io::test_read'

on:
  pull_request:
    types: [ opened, edited, synchronize ]
    paths:
      - 'tasks/main.py'
      - 'tasks/driver/files/commands.py'
      - 'tasks/driver/network/commands.py'
      - 'resources/scripts/'
      - 'tests/main/s2/test_io.py'
      - '.github/workflows/io$read.yaml'
  workflow_dispatch:

jobs:
  test-read:
    timeout-minutes: 1
    name: 'test-read'
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: dev
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest decorator requests
      - run: |
          pytest tests/main/s2/test_io.py::TestIo.py::test_read