name: '2.io::test_save'

on:
  push:
    paths:
      - './tests/main/s2/test_io.py'
      - '.github/workflows/io$save.yaml'
  workflow_dispatch:

jobs:
  test-save:
    timeout-minutes: 1
    name: 'test-save'
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: dev
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest decorator requests
      - run: |
          pytest ./tests/main/s2/test_io.py::TestIo.py::test_save