name: '2.script::test_dev'

on:
  pull_request:
    types: [ opened, edited, synchronize ]
    paths:
      - 'tasks/main.py'
      - 'tasks/driver/files/commands.py'
      - 'tasks/driver/network/commands.py'
      - 'resources/scripts/'
      - 'test/main/s2/test_script.py'
      - '.github/workflows/script$dev.yaml'
  workflow_dispatch:

jobs:
  test-dev:
    timeout-minutes: 1
    name: 'test-dev'
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: dev
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest decorator requests
      - run: |
          pytest test/main/s2/test_script.py::TestScript::test_dev