name: '3.sockets::test_send_receive'

on:
  pull-request:
    types: [ opened, edited, synchronize ]
    paths:
      - './tests/main/s3/test_sockets.py'
      - '.github/workflows/sockets$send_receive.yaml'
  workflow_dispatch:

jobs:
  test-send_receive:
    timeout-minutes: 1
    name: 'test-send_receive'
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: dev
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest decorator requests
      - run: |
          pytest ./tests/main/s3/test_sockets.py::TestSockets.py::test_send_receive